/// Flutter icons Custom
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Custom
///      fonts:
///       - asset: fonts/Custom.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Custom {
  Custom._();

  static const _kFontFam = 'Custom';
  static const String? _kFontPkg = null;

  static const IconData paper = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pen_ruler = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calender = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_220 = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);

}
